# Generated by Django 2.2.14 on 2024-01-22 11:59

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240122_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='detail_image_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='detail_image_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='detail_image_3',
        ),
        migrations.AlterField(
            model_name='item',
            name='addictional_info',
            field=mdeditor.fields.MDTextField(default=''),
        ),
    ]
